# Generated by Django 5.2.16 on 2026-07-24 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('descricao', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Terreno', 'Terreno'), ('Imóvel', 'Imóvel'), ('Veículo', 'Veículo'), ('Outro', 'Outro')], default='Terreno', max_length=20)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('valor_aquisicao', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_estimado_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bem',
                'verbose_name_plural': 'Bens',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('nome', models.CharField(max_length=120)),
                ('cor', models.CharField(default='#0d9488', max_length=7)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='financas.categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('Conta Corrente', 'Conta Corrente'), ('Poupança', 'Poupança'), ('Dinheiro', 'Dinheiro'), ('Carteira Digital', 'Carteira Digital'), ('Outro', 'Outro')], default='Conta Corrente', max_length=30)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('nome', models.CharField(max_length=120)),
                ('limite', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('dia_fechamento', models.PositiveSmallIntegerField()),
                ('dia_vencimento', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('conta_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartoes', to='financas.conta')),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('descricao', models.CharField(max_length=200)),
                ('forma_pagamento', models.CharField(choices=[('conta', 'Débito em conta'), ('cartao', 'Cartão de crédito')], default='conta', max_length=10)),
                ('tipo', models.CharField(choices=[('variavel', 'Variável'), ('fixa', 'Fixa'), ('consorcio', 'Consórcio')], default='variavel', max_length=20)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_fixo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('dia_vencimento', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('numero_parcelas', models.PositiveIntegerField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('compra_id', models.CharField(blank=True, max_length=32)),
                ('parcela_atual', models.PositiveIntegerField(blank=True, null=True)),
                ('parcela_total', models.PositiveIntegerField(blank=True, null=True)),
                ('repeticao_id', models.CharField(blank=True, max_length=32)),
                ('cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='financas.cartao')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='financas.categoria')),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='financas.conta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('descricao', models.CharField(max_length=200)),
                ('tipo_investimento', models.CharField(default='Outro', max_length=40)),
                ('operacao', models.CharField(choices=[('aporte', 'Aporte'), ('resgate', 'Resgate')], default='aporte', max_length=10)),
                ('ativo_grupo', models.CharField(blank=True, max_length=120)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_estimado_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investimentos', to='financas.conta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
                'ordering': ['-data', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tipo', models.CharField(choices=[('variavel', 'Variável'), ('fixa', 'Fixa'), ('consorcio', 'Consórcio')], default='variavel', max_length=20)),
                ('data', models.DateField(blank=True, null=True)),
                ('dia_recebimento', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('numero_parcelas', models.PositiveIntegerField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('repeticao_id', models.CharField(blank=True, max_length=32)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to='financas.categoria')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='financas.conta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['-data', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('valor_planejado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('categoria', models.ForeignKey(limit_choices_to={'tipo': 'despesa'}, on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='financas.categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['categoria__nome'],
                'unique_together': {('user', 'categoria')},
            },
        ),
    ]
