from django.urls import path

from financas.views import (
    CustomLoginView,
    CustomLogoutView,
    backup_export,
    backup_import,
    backup_view,
    bens_list,
    cartoes_list,
    categorias_list,
    contas_list,
    dashboard,
    despesas_list,
    entity_delete,
    entity_form,
    faturas_view,
    investimentos_list,
    previsao_view,
    receitas_list,
    register,
)

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('contas/', contas_list, name='contas_list'),
    path('cartoes/', cartoes_list, name='cartoes_list'),
    path('categorias/', categorias_list, name='categorias_list'),
    path('receitas/', receitas_list, name='receitas_list'),
    path('despesas/', despesas_list, name='despesas_list'),
    path('investimentos/', investimentos_list, name='investimentos_list'),
    path('bens/', bens_list, name='bens_list'),
    path('faturas/', faturas_view, name='faturas'),
    path('previsao/', previsao_view, name='previsao'),
    path('backup/', backup_view, name='backup'),
    path('backup/export/', backup_export, name='backup_export'),
    path('backup/import/', backup_import, name='backup_import'),
    path('form/<str:entity>/', entity_form, name='entity_form'),
    path('form/<str:entity>/<int:pk>/', entity_form, name='entity_form_edit'),
    path('delete/<str:entity>/<int:pk>/', entity_delete, name='entity_delete'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('register/', register, name='register'),
]
