from financas.views.auth_views import CustomLoginView, CustomLogoutView, register
from financas.views.web import (
    backup_export,
    backup_import,
    backup_view,
    bens_list,
    cartoes_list,
    categorias_list,
    contas_list,
    dashboard,
    despesas_list,
    entity_delete,
    entity_form,
    faturas_view,
    investimentos_list,
    previsao_view,
    receitas_list,
)

__all__ = [
    'CustomLoginView',
    'CustomLogoutView',
    'register',
    'dashboard',
    'contas_list',
    'cartoes_list',
    'categorias_list',
    'receitas_list',
    'despesas_list',
    'investimentos_list',
    'bens_list',
    'faturas_view',
    'previsao_view',
    'backup_view',
    'backup_export',
    'backup_import',
    'entity_form',
    'entity_delete',
]
